name: Build and Test Flask App 

on: [push]

jobs: 
  build-and-test:
    # ubuntu 18 is built on debian 10 (buster), which is what Python provides us as a docker image 
    # we'll use that here since it's the most similar environment provided by GitHub.  
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Display Python Version (should be 3.8.x)
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # this is only a simple test of the flask app itself
      - name: Test 
        run:  python -m unittest -v tests/test_api.py
  # job to test against App Engine
  test-app-engine:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Deploy to Google App Engine
        id: deploy-gae
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: app-engine.yaml
          credentials: ${{ secrets.GCP_KEY }}      
      - name: Test Google App Engine deployment 
        run: curl "${{ steps.deploy-gae.outputs.url }}"
# job to test against Functions 
  test-functions:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Deploy to Google Cloud Functions
        id: deploy-functions
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: hello_cloud
          runtime: python38
          region: europe-west3
          credentials: ${{ secrets.GCP_KEY }}      
      - name: Test Google Cloud Functions deployment 
        run: curl "${{ steps.deploy-functions.outputs.url }}"
# job to test against Cloud Run
  build-container: 
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_KEY }} 
          export_default_credentials: true 

      - name: Authorize Docker push
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Build and Push Container
        run: |
          docker build --tag europe-west3-docker.pkg.dev/cloud-variations-fs2021/hello-cloud/hello-cloud:latest .
          docker push europe-west3-docker.pkg.dev/cloud-variations-fs2021/hello-cloud/hello-cloud:latest
  test-run:
    needs: build-container
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Deploy to Google Cloud Run
        id: deploy-run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: hello-cloud-run
          image: europe-west3-docker.pkg.dev/cloud-variations-fs2021/hello-cloud/hello-cloud:latest
          region: europe-west3
          flags: --port=5000 --allow-unauthenticated 
          credentials: ${{ secrets.GCP_KEY }}      
      - name: Test Google Cloud Functions deployment 
        run: curl "${{ steps.deploy-run.outputs.url }}"

